development:
  adapter: postgresql
  encoding: unicode
  database: major_blog_app_development
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: major_blog_app_test
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000
